#%RAML 1.0 NamedExample
value:
-
  AccountName: Anusha
  AccountNumber: API-3456
  FirstName: Anusha
  MiddleName: Reddy
  LastName: Nalla
  Phone: "987654321"
  Email: anusha@gmail.com
-
  AccountName: Sireesha
  AccountNumber: API-345
  FirstName: siri
  MiddleName: racha
  LastName: venkata
  Phone: "987654"
  Email: siri@gmail.com  